### PR TITLE
Add service plugin: socket-redis

### PR DESCRIPTION
**Pull request by kris-lab**
- Number of channels
- Number of subscribers

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please have a look

**Comment by njam** [comment]
- fetch_socket_redis_stats: Rename "stats" to "status" (because of socket-redis naming convention)
- fetch_socket_redis_stats: raise:
 - Wrap url in backticks
 - Add server response (status code and body) for debugging?
- services.md: In the config docu, link the word "status" to https://github.com/cargomedia/socket-redis#status-request ?

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
- What is `response.message`? Is it useful?

**Comment by kris-lab** [comment]
`response.message` is e.g. ‘Not Found’, `Not Authenticated`, `Internal Server Error`

**Comment by njam** [comment]
Ok let's keep it then!

- Add `require 'net/http'` - probably done somewhere else already that's why it works?

**Comment by kris-lab** [comment]
We also use `response.message` in [copperegg storage](https://github.com/cargomedia/bipbip/blob/master/lib/bipbip/storage/copperegg.rb#L45) which I believe is useful.

@njam please review

**Comment by njam** [comment]
- require: Prefer single quotes :D

Rest looks good

**Comment by kris-lab** [comment]
released

**Pull request merged**
