### PR TITLE
Gearman: add "waiting" metric

### PR DESCRIPTION
**Pull request by kris-lab**
waiting = queued - active

(because queued includes active/running ones)

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please have a look - let's skip specs for this for the moment.

**Comment by kris-lab** [comment]
@njam now is ready for review. Actually introducing spec would be the right way to go.

**Comment by njam** [comment]
lgtm

Adding a spec would be great

**Comment by kris-lab** [comment]
released

**Pull request merged**
