### PR TITLE
Switch from "rb-inotify" to "ruby-inotify", use thread to read events

### PR DESCRIPTION
**Pull request by njam**

### CODE REVIEW

**Comment by njam** [comment]
Addressing #114

I'm using a different, simpler inotify wrapper, and listen to events in a separate thread.
I'm hoping this will resolve the issue with the plugin getting "stuck".

@ppp0 please review

**Comment by ppp0** [comment]
Not compatible with ruby 2.0 ?

**Comment by njam** [comment]
Hm I had this problem before I think.
My guess is that there's something strange with the travis FS.
Since these assertions are not important, I just removed them (same thing I did last time..).

**Comment by ppp0** [comment]
otherwise looks good, although I did not go into details - I reckon you have done extensive tests

**Comment by ppp0** [comment]
failed for 2.0 - this seems to be ok..

@njam mergeable?

**Comment by njam** [comment]
Let's wait with this - the idea was that this can resolve the "stuck bipbip" problem. But probably the root cause is something else: mongodb client.

**Comment by njam** [comment]
Closing as not needed

**Pull request closed without merging**
