### PR TITLE
Fix puppet plugin units

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please review

**Comment by kris-lab** [comment]
@njam please review

**Comment by kris-lab** [comment]
@njam @ppp0 please review

**Comment by njam** [comment]
Hm, same story as with mongodb-pulsar plugin - how about introducing a combined metric `all_optimal` (instead of these `has_X`)?

**Comment by kris-lab** [comment]
Ok, sounds good

@njam please review;

**Comment by kris-lab** [comment]
@njam what about now?

**Comment by njam** [comment]
lgtm - also bump version?

**Comment by kris-lab** [comment]
Version bumped https://github.com/cargomedia/bipbip/pull/90

**Pull request merged**
