### PR TITLE
All metrics should be gauges not counters

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by njam** [comment]
@ppp0 the issue remains. any updates on that ticket on zendesk?

**Comment by njam** [comment]
@ppp0 the issue remains. any updates on that ticket on zendesk?

**Comment by ppp0** [comment]
I bumped support. Issue is reproduceable but no further progress since December 31, 2014, 3:11 PM

**Comment by njam** [comment]
So they didn't respond on the ticket? Hmhmhm

**Comment by ppp0** [comment]
They responded now:

>Ph G, Aug 26, 10:26 AM:
Any progress on this issue? Thanks

>Sarmad Riaz, Aug 26, 1:22 PM:
Hi Ph,

>Unfortunately no, the case hasn't been picked up as yet. but we are moving towards certain re-architectural changes so I will make sure to get this issue prioritized and fixed. Thank you for your patience.

>Regards,
Sarmad Riaz 
Technical Support Dude at CopperEgg Corperation

**Pull request closed without merging**
