### PR TITLE
BO-203 Add fastcgi_php_apc:avail_mem_size/mem_used_purcentage metrics

### PR DESCRIPTION
**Pull request by zazabe**

### CODE REVIEW

**Comment by zazabe** [comment]
not sure how to test this... gonna try with the vagrant box available from this repo...

**Comment by ppp0** [comment]
great job!

**Comment by zazabe** [comment]
@{c7e8ab9c-90bf-4796-bb88-9aa7c8150044,Reto Kaiser} please look at 8f9508b, should be fine but i'm wondering if it would not make more sense to report the `used_mem_size` instead of `avail_mem_size` from the plugin, wdyt?

**Comment by njam** [comment]
Agree, *used* memory sounds more useful.

**Pull request merged**
