### PR TITLE
Avoid "mustermann" in version 1.0.0.beta2

### PR DESCRIPTION
**Pull request by kris-lab**
Part of https://github.com/cargomedia/puppet-packages/issues/1464

Currently `bipbip` tries to install [mustermann@1.0.0.beta2](https://rubygems.org/gems/mustermann/versions/1.0.0.beta2) which requires `ruby@2.2`.

Because of https://github.com/resque/resque/issues/1505
cc @njam @ppp0

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please review - hopefully this will solve the problem. It is quite difficult to re-produce locally

**Comment by kris-lab** [comment]
Hmm sorry, this workaround will not work anyway for ruby `1.9.3/2.0.0`. The best solution would be to avoid `beta` versions. Wdyt, any ideas?

**Comment by njam** [comment]
lgtm

**Comment by kris-lab** [comment]
Paired with @njam

**Comment by kris-lab** [comment]
released

**Pull request merged**
