### PR TITLE
Add "command/exec" plugin

### PR DESCRIPTION
**Pull request by kris-lab**
The idea is to allow plugin to run any `command`. First run should learn `schema`. Every next run should store metrics.

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam could you have a look on really skeleton implementation? Not sure how to approach the `unit` and `type` for metrics. Any thoughts?

**Comment by njam** [comment]
How about we define two modes of operation?:
- simple: values are numbers. Assume everything's `gauge`, skip `unit`. Like in [bipbip-cm](https://github.com/cargomedia/bipbip-cm/blob/master/lib/bipbip/plugin/cm.rb).
- advanced: values are hashes. With a `type`, `unit` and `value` key

Review:
- I would vote to call it `command` instead of `exec`
- Docu: Add a bit more explanation, and an example?
- exec_command: Should also check exit code. If not `0` then fail? Here's an [example](https://github.com/cargomedia/puppet-packages/blob/master/spec/vagrant_helper.rb#L80)

**Comment by kris-lab** [comment]
@njam wdyt?

**Comment by njam** [comment]
- How about detecting "mode" automatically (by checking whether it's hash or not)?
- services.md: Annotate with `json` type for code blocks.
- services.md: Rename "single" mode to "simple"?
- services.md: "`unit` type is ignored in this mode." - I would delete this phrase, it doesn't add too much value?
- services.md: Shouldn't values always be numbers (now strings)?
- bipbip/plugin/command.rb: Don't abbreviate variable names (see [guides](https://github.com/cargomedia/guides/tree/master/style#naming))
- bipbip/plugin/command.rb::find_schema: Use `map`?

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
- services.md: Drop newline after "Configuration options:" (formatting)
- services.md: command param: Put example into paranthesis (formatting, check other examples in the same file)
- services.md: Remove line "Every next run will operate normally."? IMO doesn't add important information.
- services.md: Drop newline before json code blocks, add colon at end of sentence above (check other examples in same file)
- services.md: Example values in json are a bit unclear to me. Sometimes `foo/bar` means you put either "foo" or "bar", sometimes it mean you put a variable "of type foo" or "of type bar". How about? `{"value": 12, "type": "[gauge|counter]", "unit": "<unit>"}`
- bipbip/plugin/command.rb: Don't abbreviate variable names (v, k)
- bipbip/plugin/command.rb::operation_mode: There's now an attribute, but instead of it, the property is used directly, and set from another method. Bit confusing.
 - There's no real need to "cache" the mode - it might be rather more powerful to detect it for every metric - this way they could be mixed as well?
 - Use symbols instead of strings
- plugin/command_spec.rb: To also cover the command execution - how about adding a test which executes an actual command (e.g. that `ruby` command from the readme)?

**Comment by kris-lab** [comment]
Agree. Auto detection of metric entry mode is the best solution. I tried to keep it simple by doing this predefined. Now it looks that is simpler if it is dynamic:)

@njam please have a look

**Comment by njam** [comment]
Looks good!

**Comment by kris-lab** [comment]
bumped version

**Pull request merged**
