### PR TITLE
janus rtpbroadcast: add bipbip metric for "inbound packet loss"

### PR DESCRIPTION
**Pull request by kris-lab**
Depends on cargomedia/janus-gateway-rtpbroadcast#81
Depends on https://github.com/cargomedia/janus-gateway-rtpbroadcast/pull/46
Depends on https://github.com/cargomedia/janus-gateway-rtpbroadcast/pull/82

> And maybe also for "keyframe-overdue" (to replace the logparser entry)?

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam currently `packet-loss` is expressed as `%` with value `0.00-1.00`. I am wondering how should we handle multiple streams with packet-loss. Should it be added? Then we will get value 0% up to let's say 400% if 4 streams has 100% loss?

Any preferences?

**Comment by njam** [comment]
Hm, good question. What's going to be the alerting condition? I guess we accept a certain loss per stream (let's say 1%). So if we have 4 streams we would like to alert if either the *average loss* is 1% or if the *maximum loss* is 1%.
So how about two metrics `packet-loss-avg` and `packet-loss-max`?

**Comment by kris-lab** [comment]
Hmm so:
- `packet_loss_video_avg` is average for all streams
- `packet_loss_video_max` is max value of all registered streams

**Comment by njam** [comment]
yes! wdyt?

**Comment by kris-lab** [comment]
Agree, already implemented. Wdyt?

**Comment by njam** [comment]
Unit should not be `%` because it's a rate and not a percentage. I'd suggest to either *not* specify a unit, or multiply the rate by 100. wdyt?

**Comment by kris-lab** [comment]
Let's go with `%`? Will be cleaner (more readable) in copperegg.

**Comment by njam** [comment]
lgtm

**Pull request merged**
