### PR TITLE
Expose janus/rtp plugin packet-loss count as gauge

### PR DESCRIPTION
**Pull request by kris-lab**
Depends on https://github.com/cargomedia/janus-gateway-rtpbroadcast/issues/95

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam `streams_packet_loss_audio_count` or `streams_packet_loss_audio_count_total`?
please review

**Comment by njam** [comment]
Ah it's actually a "counter" not a "gauge" :)

I don't think we need the `-total`, because it's a *counter* already.

**Comment by kris-lab** [comment]
makes sense and good catch. @njam please re-review

**Comment by njam** [comment]
lgtm

**Pull request merged**
