### PR TITLE
Fix source_identifier fo command plugin

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please have a look; the best solution would be add some of this logic to "abstract" `plugin` itself. The problem is that it will change custom metrics groups @ copperegg and will mess up a bit IMO. Current solution is a good workaround and works fine. Also I had to short `command` to around 20 characters. In our case it can be extremely long:)

**Comment by kris-lab** [comment]
btw: in the box all works fine without adding `open3` to as `add_runtime_dependency` in `gemspec`

**Comment by njam** [comment]
How about implementing this logic in `plugin.rb` - removing invalid chars, and trimming at some length?

**Comment by kris-lab** [comment]
@njam please verify

**Comment by njam** [comment]
- There's an attribute accessor for `metric_group` - so I think you can use that (`metric_group`) instead of `@metric_group`?
- Add `metric_group` even if config is empty?
- Is the 20-characters trim off really necessary? Is this a copperegg limitation?

**Comment by kris-lab** [comment]
Agree to all points. I didn't experience problems with copperegg limitation for identifier (personally I have checked length of ~120 characters only). I did trim that because it looks a bit strange in copperegg UI :)

@njam please review

**Comment by njam** [comment]
looks good

**Pull request merged**
