### PR TITLE
Mongodb: add authentication

### PR DESCRIPTION
**Pull request by kris-lab**
Part of https://github.com/cargomedia/puppet-packages/pull/1160
Part of https://github.com/cargomedia/puppet-cargomedia/pull/1072

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam wdyt?

**Comment by njam** [comment]
- What's the reasoning to drop "slave_ok" without replacement?

rest lgtm

**Comment by kris-lab** [comment]
The reason is that we connect to local instances always. We specify roles to connect `router`, `config`, rep: `secondary`, `primary`, `arbiter`. There is not need for read preferences as we read only local status.

**Comment by kris-lab** [comment]
@njam are you ok to merge this?

**Comment by njam** [comment]
yes, lgtm!

**Comment by kris-lab** [comment]
released

**Pull request merged**
