### PR TITLE
mongodb: extend metric with slow_query_max_time

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam wdyt?

`slow_queries_time_max` is calculated for whole measurement time range. So this is highest number of let's say last 5 seconds.

**Comment by njam** [comment]
- mongo.rb: call `['max']['query_time']` rather `['max']['time']` for consistency?

Rest looks good!

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
lgtm

**Comment by kris-lab** [comment]
released

**Pull request merged**
