### PR TITLE
Improve readme

### PR DESCRIPTION
**Pull request by njam**

### CODE REVIEW

**Comment by njam** [comment]
@kris-lab @ppp0 please review

I was thinking of also documenting the different metrics per plugin.
If we did that the readme would be become too long though - and we might rather need one docu page per plugin?

**Comment by kris-lab** [comment]
Looks very very good! good job @njam

**Comment by kris-lab** [comment]
Regarding specific metrics it would be good to add `docs` folder with `*.md` per plugin?

**Comment by njam** [comment]
As discussed for now I've extracted *service plugin* documentation to one separate file. Once we have metrics documentation we should introduce one `*.md` file per plugin.

**Pull request merged**
