### PR TITLE
Add puppet plugin

### PR DESCRIPTION
**Pull request by kris-lab**
See [puppet-agent-check.rb](https://github.com/cargomedia/puppet-packages/blob/master/modules/puppet/templates/agent/puppet-agent-check.rb).

Metrics:
- Age of last run
- Number of resources
- Number of failures
- Number of changes
- Missing events?

### CODE REVIEW

**Comment by njam** [comment]
- puppet.rb: puppet_last_run_summary: No need to have the `puppet_` prefix, as the file and class are already called *puppet*?
- puppet.rb: last_run_age_in_sec: Remove `_ in_sec` (we never include units in variable names - everything's SI units)
- puppet.rb: Timing information might be interesting as well - how about including total time for last run?
- puppet_spec.rb: Assert actual numbers, and not just type of variable

**Comment by kris-lab** [comment]
@njam please review;

**Comment by njam** [comment]
looks good!

**Comment by kris-lab** [comment]
pushed to rubygems

**Pull request merged**
