### PR TITLE
Handle telnet timeout exception for coturn

### PR DESCRIPTION
**Pull request by kris-lab**
Part of https://github.com/cargomedia/puppet-cargomedia/issues/1147

```
E, [2016-04-11T06:40:21.624609 #14960] ERROR -- coturn janus2.fuckbook.com::coturn::localhost: undefined method `[]' for nil:NilClass
 /var/lib/gems/1.9.1/gems/bipbip-0.6.16/lib/bipbip/plugin/coturn.rb:16:in `monitor'
 /var/lib/gems/1.9.1/gems/bipbip-0.6.16/lib/bipbip/plugin.rb:80:in `run_measurement'
 /var/lib/gems/1.9.1/gems/bipbip-0.6.16/lib/bipbip/plugin.rb:39:in `block (2 levels) in run'
 /usr/lib/ruby/1.9.1/timeout.rb:68:in `timeout'
 /var/lib/gems/1.9.1/gems/bipbip-0.6.16/lib/bipbip/plugin.rb:38:in `block in run'
 /var/lib/gems/1.9.1/gems/bipbip-0.6.16/lib/bipbip/plugin.rb:36:in `loop'
 /var/lib/gems/1.9.1/gems/bipbip-0.6.16/lib/bipbip/plugin.rb:36:in `run'
 /var/lib/gems/1.9.1/gems/bipbip-0.6.16/lib/bipbip/agent.rb:59:in `block in start_plugin'
```

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam please have a look. In general we will throw a more specific error. However it will not solve a problem. 

Maybe we should increase the timeout? Currently is default to 10 sec.

**Comment by njam** [comment]
According to the stack trace none of these errors were raised, but `data.match(…)` was `nil`.
I think we should rather check for the response data then.
Could you reproduce this? How do you know that this is due to a telnet timeout?

**Comment by kris-lab** [comment]
Currently we get ` /usr/lib/ruby/1.9.1/timeout.rb:68:in `timeout'` ?

I can reproduce `connection open timeout` with e.g. `nc -l localhost 5766` but cannot reproduce `data timeout` which might be the case. Also another case is `TCP` timeout or `EOF` which would case to return `nil` what causes `undefined method `[]' for nil:NilClass` at the end.

Hard to reproduce all of this stages so maybe `rescue` will help?

I have also checked on production but it doesn't happen.

**Comment by kris-lab** [comment]
Oh I could reproduce this finally:

````
irb(main):028:0> a=_fetch_session_data
=> "TURN Server\nCoturn-4.5.0.3 'dan Eider'\n\nType '?' for help\n> \n  Total sessions: 0\n\n> "
irb(main):029:0> a=_fetch_session_data
=> "TURN Server\nCoturn-4.5.0.3 'dan Eider'\n\nType '?' for help\n> \n  Total sessions: 0\n\n> "
irb(main):030:0> a=_fetch_session_data
=> "TURN Server\nCoturn-4.5.0.3 'dan Eider'\n\nType '?' for help\n> \n  Total sessions: 0\n\n> "
irb(main):031:0> a=_fetch_session_data
=> "TURN Server\nCoturn-4.5.0.3 'dan Eider'\n\nType '?' for help\n> \n  Total sessions: 0\n\n> "
irb(main):032:0> a=_fetch_session_data
=> "TURN Server\nCoturn-4.5.0.3 'dan Eider'\n\nType '?' for help\n> \n  Total sessions: 0\n\n> "
irb(main):033:0> a=_fetch_session_data
=> "TURN Server\nCoturn-4.5.0.3 'dan Eider'\n\nType '?' for help\n> \n  Total sessions: 0\n\n> "
irb(main):034:0> a=_fetch_session_data
=> "TURN Server\nCoturn-4.5.0.3 'dan Eider'\n\nType '?' for help\n> \n  Total sessions: 0\n\n> "
irb(main):035:0> a=_fetch_session_data
=> "TURN Server\nCoturn-4.5.0.3 'dan Eider'\n\nType '?' for help\n> \n  Total sessions: 0\n\n> "
irb(main):036:0> a=_fetch_session_data
=> "TURN Server\nCoturn-4.5.0.3 'dan Eider'\n\nType '?' for help\n> "
irb(main):037:0> a=_fetch_session_data
=> "TURN Server\nCoturn-4.5.0.3 'dan Eider'\n\nType '?' for help\n> "
irb(main):038:0> a=_fetch_session_data
=> "TURN Server\nCoturn-4.5.0.3 'dan Eider'\n\nType '?' for help\n> \n  Total sessions: 0\n\n> "
irb(main):039:0> a=_fetch_session_data
=> "TURN Server\nCoturn-4.5.0.3 'dan Eider'\n\nType '?' for help\n> \n  Total sessions: 0\n\n> "
```

Sometimes it does not return `Total sessions: 0` ?

**Comment by njam** [comment]
I think this `/usr/lib/ruby/1.9.1/timeout.rb` line in the stack is something else, it's just part of bipbip internals (called from `lib/bipbip/plugin.rb:38`).
Execution stops because of `undefined method `[]' for nil:NilClass`, so `_fetch_session_data` doesn't fail.

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
I would rather expect it to fail if the response has an unexpected format. That's what we usually do.
Otherwise we might interpret the numbers as being "0", while actually there was just no data available.
wdyt?

**Comment by kris-lab** [comment]
But isn't it what happens now? The response has unexpected format and we fail, log and re-try?

**Comment by njam** [comment]
You mean on current master? Yes that's true, and I think that's good, I would just throw a more meaningful error.
> I would suggest to detect the timeout and rethrow a more meaningful error. Bipbipb will handle the rest (log it, retry in the next interval).

**Comment by kris-lab** [comment]
ok then! agree.

**Comment by kris-lab** [comment]
@njam is it better direction to go?

**Comment by njam** [comment]
Ok why not, lgtm

**Pull request merged**
