### PR TITLE
Mongodb plugin leaks file handles

### PR DESCRIPTION
**Pull request by kris-lab**
Via https://github.com/cargomedia/puppet-cargomedia/issues/820

```sh
$ sudo lsof -p $(pgrep -f 'bipbip') | grep mongodb | wc -l
675
```

### CODE REVIEW

**Comment by ppp0** [comment]
May be communicate on UNIX sockets instead of `127.0.0.1` when on `localhost`?
(See http://docs.mongodb.org/v2.2/reference/configuration-options/#nounixsocket)

**Comment by kris-lab** [comment]
Could be an option but it could not solve the problem I guess? An issues is in driver and our implementation. We simply create a new client for every plugin iteration.

**Comment by njam** [comment]
I think the reason to reconnect every time was to make sure the connection is okay. Otherwise if the connection fails for some reason we will probably not be able to read data anymore. Unless there's some automated reconnecting mechanism?
Could you try whether they handle it?

**Comment by kris-lab** [comment]
Yes, there is built in reconnection mechanism. If connection is down it tries to restart all the time (every 500ms). I was running it for 5min and it is trying... I guess forever!

````
DEBUG -- : MONGODB | COMMAND | namespace=kris.$cmd selector={:aggregate=>"system.profile", :pipeline=>[{"$match"=>{"millis"=>{"$gte"=>0}, "ts"=>{"$gt"=>2015-06-22 16:19:44 +0000}}}, {"$group"=>{"_id"=>"null", "total_count"=>{"$sum"=>1}, "total_time"=>{"$sum"=>"$millis"}, "max_time"=>{"$max"=>"$millis"}}}], :cu... flags=[:slave_ok] limit=-1 skip=0 project=nil | runtime: 0.3481ms
DEBUG -- mongodb debian-7-amd64-default.vagrantup.com::mongodb::0_0_0_0: Data: {"btree_misses"=>0, "flushing_last_ms"=>2, "op_inserts"=>1, "op_queries"=>6773, "op_updates"=>0, "op_deletes"=>0, "op_getmores"=>0, "op_commands"=>68, "connections_current"=>3, "mem_resident"=>53, "mem_mapped"=>12442, "mem_pagefaults"=>22, "globalLock_currentQueue"=>0, "slow_queries_count"=>0.0, "slow_queries_time_avg"=>0, "slow_queries_time_max"=>0}
DEBUG -- : MONGODB | COMMAND | namespace=admin.$cmd selector={:ismaster=>1} flags=[] limit=-1 skip=0 project=nil | runtime: 0.8016ms
DEBUG -- : MONGODB | COMMAND | namespace=admin.$cmd selector={:ismaster=>1} flags=[] limit=-1 skip=0 project=nil | runtime: 0.3555ms

/etc/init.d/mongodb stop

DEBUG -- : MONGODB | IOError | runtime: 0.0048ms
DEBUG -- : MONGODB | COMMAND | namespace=admin.$cmd selector={:ismaster=>1} flags=[] limit=-1 skip=0 project=nil | runtime: 0.5183ms
DEBUG -- : MONGODB | Connection refused - connect(2) | runtime: 0.0057ms
DEBUG -- : MONGODB | COMMAND | namespace=admin.$cmd selector={:ismaster=>1} flags=[] limit=-1 skip=0 project=nil | runtime: 0.3543ms
DEBUG -- : MONGODB | Broken pipe | runtime: 0.0050ms
DEBUG -- : MONGODB | COMMAND | namespace=admin.$cmd selector={:ismaster=>1} flags=[] limit=-1 skip=0 project=nil | runtime: 0.3829ms

/etc/init.d/mongodb start

ERROR -- mongodb debian-7-amd64-default.vagrantup.com::mongodb::0_0_0_0: IOError
 /var/lib/gems/1.9.1/gems/mongo-2.0.5/lib/mongo/socket.rb:188:in `rescue in handle_errors'
 /var/lib/gems/1.9.1/gems/mongo-2.0.5/lib/mongo/socket.rb:183:in `handle_errors'
 /var/lib/gems/1.9.1/gems/mongo-2.0.5/lib/mongo/socket.rb:122:in `read'
 (...)

DEBUG -- : MONGODB | COMMAND | namespace=admin.$cmd selector={:listDatabases=>1} flags=[:slave_ok] limit=-1 skip=0 project=nil | runtime: 0.7048ms
DEBUG -- : MONGODB | COMMAND | namespace=kris.$cmd selector={:aggregate=>"system.profile", :pipeline=>[{"$match"=>{"millis"=>{"$gte"=>0}, "ts"=>{"$gt"=>2015-06-22 16:19:59 +0000}}}, {"$group"=>{"_id"=>"null", "total_count"=>{"$sum"=>1}, "total_time"=>{"$sum"=>"$millis"}, "max_time"=>{"$max"=>"$millis"}}}], :cu... flags=[:slave_ok] limit=-1 skip=0 project=nil | runtime: 0.6983ms
DEBUG -- mongodb debian-7-amd64-default.vagrantup.com::mongodb::0_0_0_0: Data: {"btree_misses"=>0, "flushing_last_ms"=>0, "op_inserts"=>1, "op_queries"=>3, "op_updates"=>0, "op_deletes"=>0, "op_getmores"=>0, "op_commands"=>4, "connections_current"=>2, "mem_resident"=>52, "mem_mapped"=>12442, "mem_pagefaults"=>3, "globalLock_currentQueue"=>0, "slow_queries_count"=>0.0, "slow_queries_time_avg"=>0, "slow_queries_time_max"=>0}
```

It looks like it is very safe like it is now implemented with re-using `Mongo::Client` which is instantiated only once!

**Comment by kris-lab** [comment]
Also docu mentions that "The drivers will reconnect on the subsequent operation" [here](https://github.com/mongodb/mongo-ruby-driver/wiki/FAQ#i-periodically-see-connection-failures-between-the-driver-and-mongodb-why-cant-the-driver-retry-the-operation-automatically)

**Comment by njam** [comment]
ok, very good then!

**Comment by kris-lab** [comment]
pushed to rubygems.

**Comment by kris-lab** [comment]
Released. Looks fine so far:
````
$admin@server:/home/admin$ sudo lsof -p $(pgrep -f 'bipbip') | grep mongodb | wc -l
2
```

**Pull request merged**
