### PR TITLE
Mongo: extend 'slow queries' metrics

### PR DESCRIPTION
**Pull request by kris-lab**

### CODE REVIEW

**Comment by kris-lab** [comment]
@njam could you have a look

**Comment by njam** [comment]
I think "average time" would be better, because it's not affected by the numbers of queries (volume), wdyt?

**Comment by kris-lab** [comment]
hmm makes sense; what about now?

**Comment by njam** [comment]
Looks okay.
How about keeping the reduce approach (will make it bit more compact)?

**Comment by kris-lab** [comment]
"reduce" instead of "aggregation"?

**Comment by kris-lab** [comment]
@njam please review

**Comment by njam** [comment]
Move `time_period` calculation up in `fetch_slow_queries_status` so it's not distorted by the time needed for the query?

**Comment by kris-lab** [comment]
Hmm I did it in purpose but not sure why:) I thought it is good to include query time.

Anyway @njam please review

**Comment by njam** [comment]
> I thought it is good to include query time.

Then we would measure too much time in every iteration I think (from the beginning of the method, once through all code, and to the end of the method).

Looks good

**Comment by kris-lab** [comment]
released

**Pull request merged**
