### PR TITLE
Add netstat error statistics

### PR DESCRIPTION
**Pull request by ppp0**
```
netstat --statistics
```

E.g. `SndbufErrors` and `RcvbufErrors`.
They only show up if present.

```
[…]
Ip:
    49942134 total packets received
    890 with invalid addresses
    0 forwarded
    0 incoming packets discarded <----------
    49889719 incoming packets delivered
    49813641 requests sent out
    71 outgoing packets dropped <----------
[…]
Udp:
    5964 packets received
    93831 packets to unknown port received.
    0 packet receive errors
    5669588 packets sent
    SndbufErrors: 12345 <----------
    RcvbufErrors: 12345 <----------
[…]
```
(this output might be different for different "netstat" versions!)

Maybe also relevant:
- /proc/net/udp
- ifconfig

Some input: http://blog.packagecloud.io/eng/2016/06/22/monitoring-tuning-linux-networking-stack-receiving-data/#monitoring-network-devices

### CODE REVIEW

**Comment by ppp0** [comment]
let's wait for CI
@njam please review

**Comment by njam** [comment]
- plugin/network.rb: Aren't these metrics *counters* (instead of *gauges*) - i.e. they increase over time?
- plugin/network.rb: "errors" sounds a bit harsh - how about "statistics"? Also let's avoid using abbreviations for variables ("e")

**Comment by njam** [comment]
As discussed let's iterate over all interfaces and sum up statistics.

**Comment by ppp0** [comment]
To be considered:
* No local interface
* Filter bonded interfaces, as they are the same interface (in our case) e.g.
```
~$ cat /sys/class/net/{bond0,eth0}/statistics/tx_packets 
473150133
473150133
```
* virtual interfaces such as `vboxnet0` 

May be make the interfaces to be excluded configurable per regex?

**Comment by ppp0** [comment]
@njam please review

**Comment by njam** [comment]
- plugin/network.rb: Now it's probably clearer and more flexible to define all metrics explicitly?
 - metrics_schema: "type" has a typo, let's add a unit
- monitor: Add a function that returns the *sum* of a certain *check* for a *list of interfaces*? Use "reduce()"?

**Comment by ppp0** [comment]
Agree it looks much better now, @njam please review

**Comment by njam** [comment]
- metrics_schema: No need to define a variable `metrics`
- monitor: No need for `data`
- _statistics_sum: I meant to add a docu block for documenting arguments and return value. See this [example](https://github.com/cargomedia/janus-gateway-ruby/blob/master/lib/janus_gateway/client.rb).

**Comment by ppp0** [comment]
@njam true, now?

**Comment by njam** [comment]
- _statistics_sum: Add return docu
- metrics_schema: Maybe add units - "Errors", and the other one is "Packets"?

**Comment by njam** [comment]
- _interfaces: let's also add docu here

Generally we try to add doc-blocks to all functions, it helps with refactoring. In bipbip it's not done in many places yet.

**Comment by ppp0** [comment]
makes sense, @njam please review

**Comment by njam** [comment]
lgtm!
please remove the dashboard before releasing

**Pull request merged**
